### PR TITLE
Adjust Log Level for LedgerFencedException in WriteEntryProcessor

### LINKED ISSUE #4326: Spammy stacetrace happened for LedgerFencedException
**BUG REPORT**

***Describe the bug***

On the Bookie we log at ERROR level the LedgerFencedException in BookieImpl.addEntry.

This is not actually a problem, it is not an ERROR in the bookie, it simply means that some client is performing recovery and there is another client that is trying to write to a fenced ledger.
We should not log this at ERROR level, that looks scary for system administartors and also pollutes the logs

```
2024-05-22T22:11:13,669+0000 [bookie-io-8-6] ERROR org.apache.bookkeeper.proto.WriteEntryProcessor - Attempt to write to fenced ledger
org.apache.bookkeeper.bookie.BookieException$LedgerFencedException: null
        at org.apache.bookkeeper.bookie.BookieException.create(BookieException.java:57) ~[org.apache.bookkeeper-bookkeeper-server-4.16.5.jar]
        at org.apache.bookkeeper.bookie.BookieImpl.addEntry(BookieImpl.java:1071) ~[org.apache.bookkeeper-bookkeeper-server-4.16.5.jar]
        at org.apache.bookkeeper.proto.WriteEntryProcessor.processPacket(WriteEntryProcessor.java:79) ~[org.apache.bookkeeper-bookkeeper-server-4.16.5.]
```
  

***To Reproduce***

Write to a fenced ledger

***Expected behavior***

Only one line, at INFO level, reporting the ID of the ledger, and possibly the client IP

Please note that on the READ path we already have these nice lines:
```
2024-05-22T22:11:18,715+0000 [BookieHighPriorityThread-OrderedExecutor-4-0] WARN  org.apache.bookkeeper.proto.ReadEntryProcessor - Ledger: 328  fenced by: /10.249.212.49:45908
2024-05-22T22:11:18,720+0000 [BookieHighPriorityThread-OrderedExecutor-3-0] WARN  org.apache.bookkeeper.proto.ReadEntryProcessor - Ledger: 327  fenced by: /10.249.212.47:42508
```

***Additional context***

BookKeeper 4.16.5

### PR DESCRIPTION
**Pull request by shoothzj**
Fix #4326 
### Motivation

Currently, when a `LedgerFencedException` occurs during the write operation, it is logged at the ERROR level in `WriteEntryProcessor`. This is misleading and unnecessarily alarming for system administrators, as a fenced ledger during recovery is an expected scenario, not an actual error condition. This change aims to reduce the severity level of such log entries to make the logs more informative and less cluttered with non-critical errors.

### Changes

- Adjusted the log level for `LedgerFencedException` in `WriteEntryProcessor` from ERROR to WARN.
- Added ledger ID and client IP information to the log message for better context and tracking.
- Corrected a typo in the comment within the same file to improve code readability.

This change makes the log output more consistent with how fenced ledgers are reported on the read path and improves the overall clarity of the log messages.

### CODE REVIEW

**Comment by shoothzj** [comment]
@dlg99 @eolivelli @hangc0276 @merlimat @nicoloboschi @StevenLuMT @zhaijack PTAL

**Review by eolivelli — APPROVED** [review]
LGTM

thank you very much ! this will save many discussions with the users and log disk space

File: bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/WriteEntryProcessor.java [hunk 1]
```diff
@@ -91,7 +91,8 @@ protected void processPacket() {
             LOG.error("Error writing {}", request, e);
             rc = BookieProtocol.EIO;
         } catch (BookieException.LedgerFencedException lfe) {
-            LOG.error("Attempt to write to fenced ledger", lfe);
+            LOG.warn("Write attempt on fenced ledger {} by client {}", request.getLedgerId(),
```
Comment (hangc0276) [inline bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/WriteEntryProcessor.java:94]: We need to print the exception

**Comment by shoothzj** [comment]
@hangc0276 If we print exception, what information we need? I see the constructor of `new LedgerFencedException` with no other information :)

```java
    public static BookieException create(int code) {
        switch(code) {
        case Code.UnauthorizedAccessException:
            return new BookieUnauthorizedAccessException();
        case Code.LedgerFencedException:
            return new LedgerFencedException();
```
