### PR TITLE
Fix error message for unrecognized number-of-bookies

### LINKED ISSUE #1925: localbookie error messages are rubbish when started incorrectly
I couldn't remember the correct invokation. It didn't help me.

```
ivan@tethra:~/Junk/bookkeeper-4.9.0-rc1/bookkeeper-all-4.9.0$ bin/bookkeeper localbookie
JAVA_HOME not set, using java from PATH. (/usr/bin/java)
ivan@tethra:~/Junk/bookkeeper-4.9.0-rc1/bookkeeper-all-4.9.0$ bin/bookkeeper localbookie -n 5
JAVA_HOME not set, using java from PATH. (/usr/bin/java)
2019-01-31 11:44:44,618 - ERROR - [main:LocalBookKeeper@477] - Exiting LocalBookKeeper because of exception in main method
java.lang.NumberFormatException: For input string: "-n"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at org.apache.bookkeeper.util.LocalBookKeeper.main(LocalBookKeeper.java:449)
java.lang.NumberFormatException: For input string: "-n"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at org.apache.bookkeeper.util.LocalBookKeeper.main(LocalBookKeeper.java:449)
```

### PR DESCRIPTION
**Pull request by liketic**
Closes #1925

### CODE REVIEW

File: bookkeeper-server/src/main/java/org/apache/bookkeeper/util/LocalBookKeeper.java [hunk 1]
```diff
@@ -428,25 +428,32 @@ private void serializeLocalBookieConfig(ServerConfiguration localBookieConfig, S
...
                 usage();
                 System.exit(-1);
             }
 
-            int numBookies = Integer.parseInt(args[0]);
+            int numBookies = 0;
+            try {
+                numBookies = Integer.parseInt(args[0]);
+            } catch (NumberFormatException nfe) {
+                LOG.error("Unrecognized number-of-bookies: " + args[0]);
```
Comment (sijie) [inline bookkeeper-server/src/main/java/org/apache/bookkeeper/util/LocalBookKeeper.java]: nit: use `{}`
```suggestion
                LOG.error("Unrecognized number-of-bookies: {}", args[0]);
```
