### PR TITLE
Fixed locking of PendingAddOp

### LINKED ISSUE #3805: LedgerCloseTest#testLedgerCloseWithConsistentLength failed with IllegalReferenceCountException
### Description
When running LedgerCloseTest, the `testLedgerCloseWithConsistentLength` failed with IllegalReferenceCountException
```
2023-02-24T16:22:04.4265552Z [ERROR] Tests run: 4, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 26.555 s <<< FAILURE! - in org.apache.bookkeeper.client.LedgerCloseTest
2023-02-24T16:22:04.4269548Z [ERROR] org.apache.bookkeeper.client.LedgerCloseTest.testLedgerCloseWithConsistentLength  Time elapsed: 2.89 s  <<< ERROR!
2023-02-24T16:22:04.4270352Z io.netty.util.IllegalReferenceCountException: refCnt: 0, increment: 1
2023-02-24T16:22:04.4270960Z 	at io.netty.util.internal.ReferenceCountUpdater.retain0(ReferenceCountUpdater.java:132)
2023-02-24T16:22:04.4271598Z 	at io.netty.util.internal.ReferenceCountUpdater.retain(ReferenceCountUpdater.java:119)
2023-02-24T16:22:04.4272204Z 	at io.netty.util.AbstractReferenceCounted.retain(AbstractReferenceCounted.java:61)
2023-02-24T16:22:04.4273013Z 	at org.apache.bookkeeper.util.ByteBufList.retain(ByteBufList.java:281)
2023-02-24T16:22:04.4273614Z 	at org.apache.bookkeeper.proto.BookieClientImpl.addEntry(BookieClientImpl.java:306)
2023-02-24T16:22:04.4274246Z 	at org.apache.bookkeeper.client.PendingAddOp.sendWriteRequest(PendingAddOp.java:148)
2023-02-24T16:22:04.4274850Z 	at org.apache.bookkeeper.client.PendingAddOp.initiate(PendingAddOp.java:263)
2023-02-24T16:22:04.4275451Z 	at org.apache.bookkeeper.client.LedgerHandle.doAsyncAddEntry(LedgerHandle.java:1358)
2023-02-24T16:22:04.4276060Z 	at org.apache.bookkeeper.client.LedgerHandle.asyncAddEntry(LedgerHandle.java:1056)
2023-02-24T16:22:04.4276673Z 	at org.apache.bookkeeper.client.LedgerHandle.asyncAddEntry(LedgerHandle.java:1051)
2023-02-24T16:22:04.4277407Z 	at org.apache.bookkeeper.client.LedgerHandle.asyncAddEntry(LedgerHandle.java:1003)
2023-02-24T16:22:04.4278133Z 	at org.apache.bookkeeper.client.LedgerCloseTest.testLedgerCloseWithConsistentLength(LedgerCloseTest.java:88)
2023-02-24T16:22:04.4278851Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-02-24T16:22:04.4279492Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2023-02-24T16:22:04.4280187Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-02-24T16:22:04.4280778Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2023-02-24T16:22:04.4281289Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
2023-02-24T16:22:04.4281871Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2023-02-24T16:22:04.4282496Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
2023-02-24T16:22:04.4283121Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2023-02-24T16:22:04.4283729Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2023-02-24T16:22:04.4284326Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
2023-02-24T16:22:04.4284945Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
2023-02-24T16:22:04.4285587Z 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
2023-02-24T16:22:04.4286148Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-02-24T16:22:04.4286586Z 	at java.base/java.lang.Thread.run(Thread.java:829)
```
Failed CI: https://github.com/apache/bookkeeper/actions/runs/4263713315/jobs/7421980838

We can reproduce it by running LedgerCloseTest all tests instead of running the `testLedgerCloseWithConsistentLength` individual test.

After I reverted https://github.com/apache/bookkeeper/pull/3784, the test passed.

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

Fix #3805

The test was failing because the updates to the object, done in the `initiate()` method, were not immediately visible to other threads. We must use synchronized consistently in all the accesses.

### CODE REVIEW

**Review by eolivelli — COMMENTED** [review]
Usually these methods are always called on the same thread. 

Adding synchronized under this assumptium shouldn't add much cost (no actual contention) so I am fine with the patch.

I wonder if you found out which is the activity who accesses this object outside of the assigned ML thread

**Review by eolivelli — APPROVED** [review]
Forget my last comment

LGTM

File: bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingAddOp.java [hunk 1]
```diff
@@ -358,7 +358,7 @@ public synchronized void writeComplete(int rc, long ledgerId, long entryId, Book
             } else {
                 LOG.warn("Failed to write entry ({}, {}) to bookie ({}, {}): {}",
                         ledgerId, entryId, bookieIndex, addr, BKException.getMessage(rc));
-                lh.handleBookieFailure(ImmutableMap.of(bookieIndex, addr));
+                lh.executeOrdered(() -> lh.handleBookieFailure(ImmutableMap.of(bookieIndex, addr)));
```
Comment (hangc0276) [inline bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingAddOp.java:361]: We shouldn't change the thread here, it will delay the handleBookieFailure process. Please check the failed test `LedgerClose2Test#testMetadataChangedDuringClose`

Comment (merlimat) [reply bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingAddOp.java]: Gotcha!

**Comment by hangc0276** [comment]
Good job!
