### PR TITLE
fix: throw reject when SingleThreadExecutor drainTo in progress and queue is empty

### LINKED ISSUE #4465: The maxPendingAddRequestsPerThread configuration is inconsistent with the actual behavior, resulting in netty direct memory OOM
**BUG REPORT**

***Describe the bug***

The maxPendingAddRequestsPerThread configuration in bookkeeper.conf is inconsistent with the actual behavior, resulting in netty direct memory OOM.

***To Reproduce***

1) set config: maxPendingAddRequestsPerThread=1000
2. simulate rocksdb failure, flush is blocked for a long time
3. addEntry requests are queued in the thread pool, and the size of queues is twice the maxPendingAddRequestsPerThread configuration
4. the size of queued requests doubled, resulting in netty direct memory OOM

***Expected behavior***

If we configure maxPendingAddRequestsPerThread to 1000, the maximum number of thread pool queues should not exceed 1000, otherwise it will cause unexpected memory usage and may cause OOM.

By reading the source code, I found that the root cause of the problem is that there is a localTasks logic in SingleThreadExecutor. Before each execution, it tries to drain all tasks from the thread pool queue to localTasks. At this time, the thread pool queue is equivalent to being cleared, but the tasks in localTasks have not yet been executed. In extreme cases, the number of tasks queued by each SingleThreadExecutor will double. I guess the purpose of using localTasks is to avoid lock contention and improve performance, which is fine. But perhaps we should consider solving the problem of doubling the number of queued tasks.

***Screenshots***
image
image
image

***Additional context***

### PR DESCRIPTION
**Pull request by nodece**
Fix #4465

### Motivaction

In `SingleThreadExecutor`, the `runner` drains all tasks from the `queue` into `localTasks`. Although the `queue` is empty in memory at this point, the tasks are still pending execution in `localTasks`—so logically, the queue is still "full."

Calling `execute()` during this phase should *not* enqueue a new `runnable` into the `queue`, as doing so would exceed the intended capacity. This can lead to increased memory usage and potential OutOfMemory (OOM) issues.

### Changes

To address this, we introduce a variable to track the total number of pending runnables. This counter is used to control whether a new task should be added:

- The counter is incremented when a runnable is added to the queue.

- The counter is decremented when a runnable is actually executed.

This ensures accurate tracking of pending tasks and prevents overfilling the logical task queue.

### CODE REVIEW

**Review by dlg99 — APPROVED** [review]

**Comment by nodece** [comment]
@lhotari Could you have a chance to review?

File: bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/SingleThreadExecutor.java [hunk 1]
```diff
@@ -213,18 +233,30 @@ public void execute(Runnable r) {
                 queue.put(r);
                 tasksCount.increment();
             } else {
-                if (queue.offer(r)) {
-                    tasksCount.increment();
+                int delta = r != null ? 1 : runnableList.size();
+                validateQueueCapacity(delta);
```
Comment (StevenLuMT) [inline bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/SingleThreadExecutor.java:237]: image
If a null is passed in here, will runnableList.size() report a NullPointerException? This may affect the function of public void execute(Runnable r)

**Review by StevenLuMT — CHANGES_REQUESTED** [review]
Boundary value confirmation is required

File: bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/SingleThreadExecutor.java (hunk 1 above)
Comment (nodece) [reply bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/SingleThreadExecutor.java]: Done.

**Review by StevenLuMT — APPROVED** [review]
LGTM

**Review by xiezhx9 — COMMENTED** [review]
squash into one commit might be better

**Comment by nodece** [comment]
> squash into one commit might be better

The code owner can use squash merge to resolve this.

File: bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/SingleThreadExecutor.java [hunk 2]
```diff
@@ -204,27 +216,89 @@ public long getFailedTasksCount() {
 
     @Override
     public void execute(Runnable r) {
+        executeRunnableOrList(r, null);
```
Comment (xiezhx9) [inline bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/SingleThreadExecutor.java:219]: How about making `executeRunnableOrList(r, null)` to `executeRunnableOrList(null, toList(r))`. This may avoid special-case handling for single runnable.

Comment (nodece) [reply bookkeeper-common/src/main/java/org/apache/bookkeeper/common/util/SingleThreadExecutor.java:219]: @xiezhx9 `toList()` is an expensive operation and should be avoided in performance-critical paths, `executeRunnableOrList()` is used only for testing purposes, so this usage is acceptable.

**Review by xiezhx9 — APPROVED** [review]

**Comment by nodece** [comment]
@lhotari @merlimat Could you have a chance to review?

**Review by StevenLuMT — APPROVED** [review]

**Review by jiazhai — APPROVED** [review]
+1. LTGM. Good Catch.
