### PR TITLE
Issue 2161: set metrics endpoint content-type

### LINKED ISSUE #2161: When httpServerEnabled=true, Prometheus reports doesn't set content-type
**BUG REPORT**

***Describe the bug***

When running with `httpServerEnabled` set to true, `/metrics` endpoint stops sending a `content-type` header (this uses the `MetricsService`, see code here https://github.com/apache/bookkeeper/blob/28dee8464764b0edceeb31ce24424f0947b5789b/bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/MetricsService.java).
With the `httpServerEnabled=false` the `PrometheusServlet` is used, and it does set a content-type header (https://github.com/apache/bookkeeper/blob/28dee8464764b0edceeb31ce24424f0947b5789b/bookkeeper-stats-providers/prometheus-metrics-provider/src/main/java/org/apache/bookkeeper/stats/prometheus/PrometheusServlet.java#L44)

 The content-type header is expected by some prometheus tools to differentiate between plaintext and protobuf formatted metrics and no content-type is considered an error.

***To Reproduce***

1. Set `httpServerEnabled=false` and enable prometheus reporter
2. run `curl localhost:8000/metrics` and notice that a content-type header is set
3. Set `httpServerEnabled=true` and enable prometheus reporter
4. run `curl localhost:8000/metrics -v` notice that there is no content-type header set

***Expected behavior***

I expect a content-type header

It seems like the statsProvider interface should have a method for allowing to set headers on the response. Default to a given content type might cause problems with other providers.

### PR DESCRIPTION
**Pull request by tomjo**
### Motivation

Fixes #2161

### Changes

Add contentType to **HttpServiceResponse** and map it in **VertxAbstractHandler** which allows
**MetricsService** (which is used instead of **PrometheusServlet** when bookie http server is enabled) to set the http **Content-Type** header to the right value which allow successful scraping of the endpoint by e.g. New Relic

Master Issue: #2161

### CODE REVIEW

**Review by merlimat — APPROVED** [review]

**Review by shoothzj — APPROVED** [review]

File: bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/MetricsService.java [hunk 1]
```diff
@@ -65,6 +67,7 @@ public HttpServiceResponse handle(HttpServiceRequest request) throws Exception {
             statsProvider.writeAllMetrics(writer);
             writer.flush();
             response.setCode(StatusCode.OK);
+            response.setContentType(PROMETHEUS_CONTENT_TYPE_004);
```
Comment (hangc0276) [inline bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/MetricsService.java:70]: Use `TextFormat.CONTENT_TYPE_004` instead of defining a new one. Just like: https://github.com/apache/bookkeeper/blob/eb27e6ed3ccd1ee46f372ae6fd0a53ccea81908f/stats/bookkeeper-stats-providers/prometheus-metrics-provider/src/main/java/org/apache/bookkeeper/stats/prometheus/PrometheusServlet.java#L42

**Review by hangc0276 — APPROVED** [review]

File: bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/MetricsService.java (hunk 1 above)
Comment (tomjo) [reply bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/MetricsService.java:70]: This will require dependency changes wasn't sure of that. I can either change the scope of the org.apache.bookkeeper.stats:prometheus-metrics-provider artifact to non-test or add an explicit dependency on io.prometheus:simpleclient_common

Comment (tomjo) [reply bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/MetricsService.java]: I chose the former approach.

File: bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/MetricsService.java [hunk 2]
```diff
@@ -65,6 +66,7 @@ public HttpServiceResponse handle(HttpServiceRequest request) throws Exception {
             statsProvider.writeAllMetrics(writer);
             writer.flush();
             response.setCode(StatusCode.OK);
+            response.setContentType(TextFormat.CONTENT_TYPE_004);
```
Comment (eolivelli) [inline bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/MetricsService.java:69]: we really have to add a new jar only for a string constant ?
I think that it is overkill

can we drop the jar and use a normal string here ?

**Review by eolivelli — CHANGES_REQUESTED** [review]
LGTM

File: bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/MetricsService.java (hunk 2 above)
Comment (tomjo) [reply bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/MetricsService.java:69]: I can revert those changes, are the maintainers in agreement? @hangc0276

Comment (hangc0276) [reply bookkeeper-server/src/main/java/org/apache/bookkeeper/server/http/service/MetricsService.java:69]: Sorry, I forgot it will introduce a new dependency. I agree to revert those changes.

**Comment by hangc0276** [comment]
@eolivelli Would you please review this PR again? Thanks.

**Review by eolivelli — APPROVED** [review]
Looks great 

+1

**Comment by lhotari** [comment]
Until this change is available, it's possible to configure `fallbackScrapeProtocol` in Prometheus at multiple levels. Here's an example for Apache Pulsar Helm chart https://github.com/apache/pulsar-helm-chart/pull/577 .
