### PR TITLE
Issue 1703: IllegalReferenceCountException at closing EntryLogManagerForSingleEntryLog

### LINKED ISSUE #1703: IllegalReferenceCountException at closing EntryLogManagerForSingleEntryLog
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do?

run bookkeeper standalone

- What did you expect to see?

bookkeeper runs well and no surprise in the log

- What did you see instead?

```
2018-09-24 19:03:58,116 - WARN  [component-shutdown-thread:Slf4JLogger@146] - Failed to release a message: PooledUnsafeDirectByteBuf(freed)
io.netty.util.IllegalReferenceCountException: refCnt: 0, increment: 1
        at io.netty.buffer.AbstractReferenceCountedByteBuf.release0(AbstractReferenceCountedByteBuf.java:100)
        at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:84)
        at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:88)
        at io.netty.util.ReferenceCountUtil.safeRelease(ReferenceCountUtil.java:113)
        at org.apache.bookkeeper.bookie.BufferedChannel.close(BufferedChannel.java:91)
        at org.apache.bookkeeper.util.IOUtils.close(IOUtils.java:48)
        at org.apache.bookkeeper.bookie.EntryLogManagerForSingleEntryLog.forceClose(EntryLogManagerForSingleEntryLog.java:221)
        at org.apache.bookkeeper.bookie.EntryLogger.shutdown(EntryLogger.java:1087)
        at org.apache.bookkeeper.bookie.InterleavedLedgerStorage.shutdown(InterleavedLedgerStorage.java:186)
        at org.apache.bookkeeper.bookie.SortedLedgerStorage.shutdown(SortedLedgerStorage.java:124)
        at org.apache.bookkeeper.bookie.Bookie.shutdown(Bookie.java:1099)
        at org.apache.bookkeeper.bookie.Bookie.shutdown(Bookie.java:1068)
        at org.apache.bookkeeper.proto.BookieServer.shutdown(BookieServer.java:201)
        at org.apache.bookkeeper.server.service.BookieService.doClose(BookieService.java:71)
        at org.apache.bookkeeper.common.component.AbstractLifecycleComponent.close(AbstractLifecycleComponent.java:109)
        at org.apache.bookkeeper.common.component.LifecycleComponentStack.lambda$close$4(LifecycleComponentStack.java:123)
        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408)
        at org.apache.bookkeeper.common.component.LifecycleComponentStack.close(LifecycleComponentStack.java:123)
        at org.apache.bookkeeper.common.component.ComponentStarter$ComponentShutdownHook.run(ComponentStarter.java:46)
        at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by sijie**
Descriptions of the changes in this PR:

*Motivation*

Fixes #1703.

The active entry log channel in EntryLogManagerForSingleEntryLog is closed twice during shutdown.
One is by EntryLogManagerForSingleEntryLog#close and the other one is EntryLogManagerForSingleEntryLog#forceClose().

*Changes*

This change is adding logic in BufferedChannel to make sure BufferedChannel can be closed multiple times.

> ---
> In order to uphold a high standard for quality for code contributions, Apache BookKeeper runs various precommit
> checks for pull requests. A pull request can only be merged when it passes precommit checks. However running all
> the precommit checks can take a long time, some trivial changes don't need to run all the precommit checks. You
> can check following list to skip the tests that don't need to run for your pull request. Leave them unchecked if
> you are not sure, committers will help you:
>
> - [ ] [skip bookkeeper-server bookie tests]: skip testing `org.apache.bookkeeper.bookie` in bookkeeper-server module.
> - [ ] [skip bookkeeper-server client tests]: skip testing `org.apache.bookkeeper.client` in bookkeeper-server module.
> - [ ] [skip bookkeeper-server replication tests]: skip testing `org.apache.bookkeeper.replication` in bookkeeper-server module.
> - [ ] [skip bookkeeper-server tls tests]: skip testing `org.apache.bookkeeper.tls` in bookkeeper-server module.
> - [ ] [skip bookkeeper-server remaining tests]: skip testing all other tests in bookkeeper-server module.
> - [ ] [skip integration tests]: skip docker based integration tests. if you make java code changes, you shouldn't skip integration tests.
> - [ ] [skip build java8]: skip build on java8. *ONLY* skip this when *ONLY* changing files under documentation under `site`.
> - [ ] [skip build java9]: skip build on java9. *ONLY* skip this when *ONLY* changing files under documentation under `site`.
> ---

> ---
> Be sure to do all of the following to help us incorporate your contribution
> quickly and easily:
>
> If this PR is a BookKeeper Proposal (BP):
>
> - [ ] Make sure the PR title is formatted like:
>     `<BP-#>: Description of bookkeeper proposal`
>     `e.g. BP-1: 64 bits ledger is support`
> - [ ] Attach the master issue link in the description of this PR.
> - [ ] Attach the google doc link if the BP is written in Google Doc.
>
> Otherwise:
> 
> - [ ] Make sure the PR title is formatted like:
>     `<Issue #>: Description of pull request`
>     `e.g. Issue 123: Description ...`
> - [ ] Make sure tests pass via `mvn clean apache-rat:check install spotbugs:check`.
> - [ ] Replace `<Issue #>` in the title with the actual Issue number.
> 
> ---

### CODE REVIEW

**Comment by sijie** [comment]
@reddycharan I think this is related to multiple entry log changes. Can you take a look?

File: bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogManagerForSingleEntryLog.java [hunk 1]
```diff
@@ -211,9 +211,7 @@ void flushRotatedLogs() throws IOException {
 
     @Override
     public void close() throws IOException {
-        if (activeLogChannel != null) {
-            activeLogChannel.close();
-        }
+        IOUtils.close(log, activeLogChannel);
```
Comment (dlg99) [inline bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogManagerForSingleEntryLog.java]: unrelated note.
With current method definition
```java
    public static void close(Logger log, java.io.Closeable... closeables) {
```

java will create new Object[] for single closeable that is passed to the method.
We'll benefit from a variant that takes only one parameter. Do we ever use this method with more than one closeable?

**Comment by reddycharan** [comment]
i vaguely remember raising concern about this issue in this fix in @merlimat fix - https://github.com/apache/bookkeeper/pull/1414

File: bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BufferedChannel.java [hunk 2]
```diff
@@ -88,8 +90,12 @@ public BufferedChannel(FileChannel fc, int writeCapacity, int readCapacity, long
 
     @Override
     public synchronized void close() throws IOException {
+        if (closed) {
```
Comment (dlg99) [inline bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BufferedChannel.java]: why is it being called more than one time in the first place?
Can we address that issue (root cause) instead of providing work around?

File: bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogManagerForSingleEntryLog.java (hunk 1 above)
Comment (reddycharan) [inline bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogManagerForSingleEntryLog.java]: why did you change this? now there is no difference between close() and forceClose() method

File: bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BufferedChannel.java (hunk 2 above)
Comment (reddycharan) [inline bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BufferedChannel.java]: hmm..not sure why it is needed. Following calls are supposed to be idempotent right?

```
ReferenceCountUtil.safeRelease(writeBuffer);
fileChannel.close();
```

Comment (dlg99) [reply bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BufferedChannel.java]: @reddycharan safeRelease() is not idempotent.
All it does is suppresses exception and logs it:

```
    public static void safeRelease(Object msg) {
        try {
            release(msg);
        } catch (Throwable t) {
            logger.warn("Failed to release a message: {}", msg, t);
        }
    }
```

The only "benefit" we are getting form it (vs .release()) is that it hides the problem.

File: bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogManagerForSingleEntryLog.java (hunk 1 above)
Comment (sijie) [reply bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogManagerForSingleEntryLog.java]: you are right. will revert it back

Comment (sijie) [reply bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogManagerForSingleEntryLog.java]: > java will create new Object[] for single closeable that is passed to the method.

yes, but it is probably okay since we use this method at shutdown phase.

> We'll benefit from a variant that takes only one parameter.

definitely we will benefit from it. +1

File: bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BufferedChannel.java (hunk 2 above)
Comment (sijie) [reply bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BufferedChannel.java]: it can probably double closed because the way we managed `try() finally {}` at shutting down entry log manager. we can fix the logic there. however I don't think that is a redirection to go, because if close() is being called twice in different places, the problem still exists. so I went down to this path to make close idempotent in the base class, which it will address the problem of now and any potentially problems in future.

Comment (eolivelli) [reply bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BufferedChannel.java]: I agree with Sikie

Comment (dlg99) [reply bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BufferedChannel.java]: ok, accepted.

**Comment by sijie** [comment]
@reddycharan I reverted the change of `close`. please take look at this PR again?

**Comment by eolivelli** [comment]
Still +1
