### PR TITLE
fix duplicate typeline for prometheus type

### LINKED ISSUE #3136: second TYPE line for metric name when use metricbeat prometheus module
***Describe the bug***
second TYPE line for metric name when use metricbeat prometheus module

### PR DESCRIPTION
**Pull request by Shoothzj**
Fixes #3136 

Descriptions of the changes in this PR:

### Motivation

fix duplicate typeline for prometheus type

### Changes

remember the prometheus type, record in set, incase print again

Master Issue: #3136

### CODE REVIEW

**Comment by Shoothzj** [comment]
@eolivelli @dlg99 PTAL

**Review by dlg99 — APPROVED** [review]

File: bookkeeper-stats-providers/prometheus-metrics-provider/src/main/java/org/apache/bookkeeper/stats/prometheus/PrometheusMetricsProvider.java [hunk 1]
```diff
@@ -172,6 +172,7 @@ public StatsLogger getStatsLogger(String scope) {
 
     @Override
     public void writeAllMetrics(Writer writer) throws IOException {
+        PrometheusTextFormatUtil.reset();
```
Comment (eolivelli) [inline bookkeeper-stats-providers/prometheus-metrics-provider/src/main/java/org/apache/bookkeeper/stats/prometheus/PrometheusMetricsProvider.java:175]: This is a sign of something going wrong.

What happens with two concurrent calls to this method?

**Review by eolivelli — CHANGES_REQUESTED** [review]

File: bookkeeper-stats-providers/prometheus-metrics-provider/src/main/java/org/apache/bookkeeper/stats/prometheus/PrometheusMetricsProvider.java (hunk 1 above)
Comment (Shoothzj) [reply bookkeeper-stats-providers/prometheus-metrics-provider/src/main/java/org/apache/bookkeeper/stats/prometheus/PrometheusMetricsProvider.java:175]: @eolivelli you are right, we don't know what will happen. Let me push a fix.

**Comment by Shoothzj** [comment]
@eolivelli PTAL again thanks, I refractor `PrometheusTextFormatUtil` to `PrometheusTextFormat` to make it can serve two concurrent calls.

For an alternate approach, I can add HashSet params to every method in `PrometheusTextFormatUtil`. I think that the former is better.

**Review by eolivelli — APPROVED** [review]
Lgtm
