### PR TITLE
issue #2879 : let bookie quit if journal thread exit

### LINKED ISSUE #2879: Journal thread exit while bookie is still on
**BUG REPORT**
Bookie does not exist when the on journal thread exists.
***Describe the bug***
I have a bookie which has three directories, after running for some days, the bookie is not healthy when test by 
```shell
bin/bookkeeper shell bookiesanity 
```
And the jstack show almost all `bookie-io` thread are waiting for journal adding an entry to the queue.

```
"bookie-io-1-20" #44 prio=5 os_prio=0 tid=0x00007f4741f02800 nid=0x57d8 waiting on condition [0x00007f46f7074000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000005778a3c88> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ArrayBlockingQueue.put(ArrayBlockingQueue.java:353)
	at org.apache.bookkeeper.bookie.Journal.logAddEntry(Journal.java:863)
	at org.apache.bookkeeper.bookie.Journal.logAddEntry(Journal.java:852)
	at org.apache.bookkeeper.bookie.Journal.logAddEntry(Journal.java:842)
	at org.apache.bookkeeper.bookie.Bookie.addEntryInternal(Bookie.java:1265)
```
And also, there are only two threads for the journal left which means one journal thread exists.
So, all `addEntry` requests to this journal will be blocked after the queue is full, and eventually, all `bookie-io` threads will be blocked.

***Expected behavior***

Bookie should suicide at the point the journal thread exit .

***Additional context***

### PR DESCRIPTION
**Pull request by aloyszhang**
Descriptions of the changes in this PR:
fix #2879 
This pull request let bookie quit when there's journal thread exit

### Motivation

As described in #2879, now if a bookie has multi journal directories means it has multi journal thread. Once a journal thread exits, the bookie will be unhealthy due to the block of all bookie-io threads, and then the bookie will not work but progress is still alive.
This pull request tries to fix this problem.

### Changes

check the journal thread alive in a fixed interval, let bookie quit once there's a journal thread exit

### CODE REVIEW

**Comment by Vanlightly** [comment]
We don't need a new configuration for this. This kind of thing should be a hidden implementation detail, there is no benefit to allowing users to configure an interval.

Another approach would be something like passing a single CountdownLatch to each journal that can be waited on from the bookie thread.

Also note that any dependency changes need to be added to Gradle or won't compile.

**Comment by aloyszhang** [comment]
@Vanlightly 
CountdownLatch sounds good. Thanks for your suggestions.

**Comment by aloyszhang** [comment]
I'm not familiar with gradle and I'll check the dependency problem first.

File: bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java [hunk 1]
```diff
@@ -714,12 +717,14 @@ public BookieImpl(ServerConfiguration conf, StatsLogger statsLogger,
...
-
+        this.journalExistCountDown = new CountDownLatch(1);
         // instantiate the journals
         journals = Lists.newArrayList();
         for (int i = 0; i < journalDirectories.size(); i++) {
-            journals.add(new Journal(i, journalDirectories.get(i),
-                    conf, ledgerDirsManager, statsLogger.scope(JOURNAL_SCOPE), allocator));
+            Journal journal = new Journal(i, journalDirectories.get(i),
+                    conf, ledgerDirsManager, statsLogger.scope(JOURNAL_SCOPE), allocator);
+            journal.setThreadAliveCounterDown(journalExistCountDown);
```
Comment (Vanlightly) [inline bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java:726]: Better for dependencies to be injected through the constructor. Tests use one constructor, which doesn't need the latch, and the BookieImpl uses the other. So you won't need to update lots of tests.

Comment (aloyszhang) [reply bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java]: Actually, if we decide whether a bookie thread should exit by the CountDownLatch,  many behaviours in the unit test are broken even if `Journal` has two constructors. 
For lots of tests, the `Journal` does not have the CountDownLatch,  shutdown the `BookieImpl` or stop the `BookieServer` will be blocked.

**Review by Vanlightly — CHANGES_REQUESTED** [review]
The JournalAliveListener approach looks good. Should it be named JournalDeathListener though? We do need to check that concurrent invocations to shutdown() either directly due to BookieServer shutdown or a journal exiting is handled. There is already handling for multiple invocations of triggerBookieShutdown, but not from that and a BookierServer shutdown. BookieServer.shutdown() should block on an already in-progress BookieImpl.shutdown() to avoid the Java process exiting too soon.

File: dependencies.gradle [hunk 2]
```diff
@@ -84,6 +84,7 @@ depVersions = [
     vertx: "3.9.8",
     yahooDatasketches: "0.8.3",
     zookeeper: "3.6.2",
+    awaitility: "4.0.2",
```
[the remark this answers is not in the document]
Comment (aloyszhang) [reply dependencies.gradle:87]: fixed

File: dependencies.gradle [hunk 3]
```diff
@@ -174,6 +175,7 @@ depLibs = [
     metricsJvm: "io.dropwizard.metrics:metrics-jvm:${depVersions.dropwizard}",
     metricsGraphite: "io.dropwizard.metrics:metrics-graphite:${depVersions.dropwizard}",
     mockito: "org.mockito:mockito-core:${depVersions.mockito}",
+    awaitility: "org.awaitility:awaitility:${depVersions.awaitility}",
```
[the remark this answers is not in the document]
Comment (aloyszhang) [reply dependencies.gradle:178]: fixed

File: bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java [hunk 4]
```diff
@@ -702,6 +704,67 @@ public Journal(int journalIndex, File journalDirectory, ServerConfiguration conf
         this.journalStats = new JournalStats(statsLogger);
     }
 
+    public Journal(int journalIndex, File journalDirectory, ServerConfiguration conf,
```
[the remark this answers is not in the document]
Comment (aloyszhang) [reply bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java:707]: fixed

File: bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java [hunk 5]
```diff
@@ -1179,12 +1196,12 @@ public void run() {
     public int shutdown() {
         return shutdown(ExitCode.OK);
     }
-
+    private final AtomicBoolean shuttingDown = new AtomicBoolean(false);
```
[the remark this answers is not in the document]
Comment (aloyszhang) [reply bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java:1199]: fixed

File: bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java [hunk 6]
```diff
@@ -715,13 +716,23 @@ public BookieImpl(ServerConfiguration conf, StatsLogger statsLogger,
             }
         }
 
-        // instantiate the journals
         journals = Lists.newArrayList();
-        for (int i = 0; i < journalDirectories.size(); i++) {
-            journals.add(new Journal(i, journalDirectories.get(i),
-                    conf, ledgerDirsManager, statsLogger.scope(JOURNAL_SCOPE), allocator));
+        if (listenJournalAlive) {
```
[the remark this answers is not in the document]
Comment (aloyszhang) [reply bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java]: fixed

File: bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (aloyszhang) [reply bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java]: After checking again, we can't use the `shutdownTriggered`. Since if `triggerBookieShutdown` invokes `shutdown`, `shutdownTriggered` will use twice, and will block `shutdown`

**Comment by Vanlightly** [comment]
@aloyszhang I mentioned in a previous comment that we need to ensure that if a shutdown is trigger by an OS signal, but a shutdown is in progress, then it needs to wait for that shutdown to complete, else the process may exit before the shutdown is complete. I didn't see that the BookieImpl.shutdown() method is synchronized but it is, and so should do that blocking for us.

Being synchronized also means that we shouldn't need that AtomicBoolean `shuttingDown` as if only one thread can execute it at a time then the `isRunning()` check is enough. However, when I tested it I found that two threads were able to enter the method concurrently! This seems due to the `this.join()` as that is the moment when another thread is permitted to enter the method. So synchronized isn't doing the job for us. The AtomicBoolean you added also isn't enough because we need an OS signal triggered shutdown to be blocked until an in-progress shutdown is completed.

So that leads us to using an explicit lock on the shutdown method to replace `synchronized` and the AtomicBoolean you added. With those changes, we should have everything covered.

Note that I have done a test of a crashing journal followed by an OS sigint and the bookie does terminate before the shutdown was completed, so this is something that does need addressing.

**Comment by aloyszhang** [comment]
@Vanlightly 

> This seems due to the this.join() as that is the moment when another thread is permitted to enter the method. So synchronized isn't doing the job for us. 

Yes, the original `synchronized ` does not work due to the join().

> Note that I have done a test of a crashing journal followed by an OS signal and the bookie does terminate before the shutdown was completed, so this is something that does need addressing.

Do you mean that there is a common shutdown in progress which invoked by the stop command `bookkeeper-deamon stop bookie`, at the same time, the journal thread crashed due to os failure, and the bookie server will shutdown without waiting for the common shutdown to complete.

**Comment by Vanlightly** [comment]
@aloyszhang Exactly, if the `triggerBookieShutdown` happens first, which can happen due to a number of reasons, and then while it is in progress an operator initiates a controlled shutdown then the bookie can terminate before the BookieImpl shutdown is complete.

**Comment by aloyszhang** [comment]
[PR Validation](https://pipelines.actions.githubusercontent.com/EMeCU0s3nV8mEzpqEGqbbDjtOUKCLJV4IPXg8mh4qtgdpzCGW6/_apis/pipelines/1/runs/15672/signedlogcontent/2?urlExpires=2021-11-18T18%3A24%3A00.7029144Z&urlSigningMethod=HMACV1&urlSignature=avrDweCvI23lkG87qvsLU2tMkCI1yAvG197gadU2atY%3D) failed.  But from the log, I can't find any useful things. Can you help with this?

**Comment by Vanlightly** [comment]
@aloyszhang run this to get the report: `./gradlew bookkeeper-server:spotbugsMain`

**Comment by aloyszhang** [comment]
@Vanlightly Validation issue has been resolved, PTAL, thanks!

**Comment by Vanlightly** [comment]
@aloyszhang An exception thrown during the shutdown would leave the CountdownLatch at 1, blocking the second caller. I would replace the AtomicBoolean and CountdownLatch with a simple lock, that is acquired before `if (isRunning())` and that would do everything needed.

File: bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java [hunk 7]
```diff
@@ -1184,56 +1184,50 @@ public int shutdown() {
     }
     // internal shutdown method to let shutdown bookie gracefully
     // when encountering exception
-    AtomicBoolean shuttingDown = new AtomicBoolean(false);
-    private final CountDownLatch countDownLatch = new CountDownLatch(1);
+    ReentrantLock lock = new ReentrantLock(true);
     int shutdown(int exitCode) {
         try {
+            lock.lock();
```
Comment (Vanlightly) [inline bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java:1190]: The lock should be placed before the try.

Comment (aloyszhang) [reply bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java]: fixed

**Comment by aloyszhang** [comment]
@Vanlightly PTAL

**Review by Vanlightly — APPROVED** [review]
LGTM
@eolivelli @nicoloboschi PTAL

**Comment by aloyszhang** [comment]
CC @eolivelli PTAL, thanks!

**Review by eolivelli — APPROVED** [review]
LGTM

can you please resolve the conflicts ?
the patch is ready to be merged

**Comment by aloyszhang** [comment]
after rebase the master branch, there're some test failed, I'll resolve this soon.

**Comment by dlg99** [comment]
@aloyszhang Please rebase/resolve merge conflicts

**Comment by aloyszhang** [comment]
Sorry for late, I'll do this soon

**Review by Shoothzj — APPROVED** [review]

**Comment by hangc0276** [comment]
ping @aloyszhang, Would you please rebase the master?

File: bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java [hunk 8]
```diff
@@ -849,12 +852,13 @@ public void run() {
     public int shutdown() {
         return shutdown(ExitCode.OK);
     }
-
     // internal shutdown method to let shutdown bookie gracefully
     // when encountering exception
-    synchronized int shutdown(int exitCode) {
+    ReentrantLock lock = new ReentrantLock(true);
+    int shutdown(int exitCode) {
```
Comment (hangc0276) [inline bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java:858]: Why use `ReentrantLock` instead of `synchronized` ?

File: pom.xml [hunk 9]
```diff
@@ -172,6 +172,7 @@
     <spotbugs-annotations.version>4.6.0</spotbugs-annotations.version>
     <javax-annotations-api.version>1.3.2</javax-annotations-api.version>
     <testcontainers.version>1.15.1</testcontainers.version>
+    <awaitility.version>4.0.2</awaitility.version>
```
Comment (hangc0276) [inline pom.xml:175]: duplicated import

File: pom.xml [hunk 10]
```diff
@@ -767,6 +768,11 @@
         <artifactId>jsoup</artifactId>
         <version>${jsoup.version}</version>
       </dependency>
+      <dependency>
```
Comment (hangc0276) [inline pom.xml:771]: duplicated import

File: bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java (hunk 8 above)
Comment (aloyszhang) [reply bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java:858]: > I think the bad case is that if a journal crash first and already triggers BookieImpl.triggerBookieShutdown(), then we shutdown bookie by the command bookkeeper-deamon stop bookie, the shutdown progress by the command may not execute completely. 

This is the reason.

**Comment by zymap** [comment]
@aloyszhang Could you rebase the master and address the comment?

**Review by StevenLuMT — APPROVED** [review]
nice

**Review by StevenLuMT — CHANGES_REQUESTED** [review]
check failed,please rebase from the newest master branch

image

**Review by hangc0276 — APPROVED** [review]
Good job!
