### PR TITLE
Fix NPE in PendingAddOp.maybeTimeout() when clientCtx is null after recycling

### LINKED ISSUE #4759: NullPointerException in PendingAddOp.maybeTimeout when clientCtx is null after recycling
## Summary

A recurring `NullPointerException` is thrown from the `monitorPendingAddOps`
scheduled task when `PendingAddOp.maybeTimeout` dereferences `clientCtx`,
which has already been cleared to `null` by `recyclePendAddOpObject()`.

## Stack trace (verbatim)

```
WARNING: Unexpected throwable from task class com.google.common.util.concurrent.MoreExecutors$ScheduledListeningDecorator$NeverSuccessfulListenableFutureTask: Cannot invoke "org.apache.bookkeeper.client.ClientContext.getConf()" because "this.clientCtx" is null
java.lang.NullPointerException: Cannot invoke "org.apache.bookkeeper.client.ClientContext.getConf()" because "this.clientCtx" is null
	at org.apache.bookkeeper.client.PendingAddOp.maybeTimeout(PendingAddOp.java:157)
	at org.apache.bookkeeper.client.LedgerHandle.monitorPendingAddOps(LedgerHandle.java:2059)
	at org.apache.bookkeeper.client.LedgerHandle.lambda$initializeWriteHandleState$0(LedgerHandle.java:290)
	at com.google.common.util.concurrent.MoreExecutors$ScheduledListeningDecorator$NeverSuccessfulListenableFutureTask.run(MoreExecutors.java:625)
	at org.apache.bookkeeper.common.util.SingleThreadSafeScheduledExecutorService$SafeRunnable.run(SingleThreadSafeScheduledExecutorService.java:46)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:369)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:310)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1474)
```

## Affected version

**BookKeeper 4.17.3** (first observed after BK 4.17.3 upgraded Netty from
4.1.121.Final to 4.1.130.Final via PR #4699). The same NPE potential exists
in 4.17.2 code but does not manifest in practice with Netty 4.1.121.

## Root cause analysis

`LedgerHandle.initializeWriteHandleState` (line 290) schedules a recurring
task that calls `monitorPendingAddOps` at `timeoutMonitorIntervalSec`
intervals. That method iterates over the `ConcurrentLinkedQueue<PendingAddOp>
pendingAddOps` and calls `op.maybeTimeout()` on each entry.

`PendingAddOp.maybeTimeout` (line 157) accesses `this.clientCtx.getConf()`.

`recyclePendAddOpObject()` (called when an op completes) sets `clientCtx =
null`. The op is removed from `pendingAddOps` by `sendAddSuccessCallbacks`
*before* the user callback fires, so in theory the monitor should never see
a recycled op. However, the `ConcurrentLinkedQueue` iterator is weakly
consistent: it can reflect concurrent modifications mid-traversal. Under high
write throughput with Netty 4.1.130 (faster I/O completion callbacks), the
window between the iterator "seeing" an op and the scheduler thread calling
`maybeTimeout` on it is wide enough for the recycling to complete first, so
`clientCtx` is already null when the call arrives.

## Observed impact

- No impact on write throughput — the NPE is swallowed by `SafeRunnable` and
  the scheduler keeps re-firing.
- The timeout monitor is silently disabled for any add op encountered in the
  null-`clientCtx` state; a genuinely timed-out op may therefore hang
  indefinitely rather than receive a `BKTimeoutException`.
- One WARNING log line + full stack trace every ~14 seconds floods pod logs.

## Suggested fix

Add a null guard in `PendingAddOp.maybeTimeout` (or at the call site in
`LedgerHandle.monitorPendingAddOps`):

```java
// PendingAddOp.java — maybeTimeout
boolean maybeTimeout() {
    if (clientCtx == null) {
        // op already recycled/reset; skip timeout check
        return false;
    }
    if (MathUtils.elapsedNanos(requestTimeNanos) >= clientCtx.getConf().addEntryQuorumTimeoutNanos) {
        timeoutQuorumWait();
        return true;
    }
    return false;
}
```

Alternatively, the `recyclerHandle.recycle(this)` call at the end of
`recyclePendAddOpObject` could be deferred until after the op has been
confirmed absent from `pendingAddOps`, eliminating the race entirely.

### PR DESCRIPTION
**Pull request by eolivelli**
## Motivation

`monitorPendingAddOps()` iterates over the `pendingAddOps` queue and calls
`maybeTimeout()` on each op. Concurrently, `sendAddSuccessCallbacks()` can
remove a completed op from the queue, call `submitCallback()` on it, and
ultimately trigger `recyclePendAddOpObject()` which sets `clientCtx = null`
(and `lh = null`, etc.).

If the scheduler thread still holds a live iterator reference to the same op
and then calls `maybeTimeout()`, dereferencing `clientCtx` causes a
`NullPointerException`:

```
java.lang.NullPointerException
    at org.apache.bookkeeper.client.PendingAddOp.maybeTimeout(PendingAddOp.java:157)
    at org.apache.bookkeeper.client.LedgerHandle.monitorPendingAddOps(LedgerHandle.java:2063)
```

The race is only triggered when `addEntryQuorumTimeoutNanos > 0` (i.e. the
quorum-timeout monitor is actually scheduled). It became reliably observable
with **Netty 4.1.130**, which changed `Recycler` thread-scheduling behavior
and narrowed the window enough to expose the pre-existing race.

Closes #4759.

### `PendingAddOp.java`

* **`maybeTimeout()` — snapshot `clientCtx` into a local.**
  A naive null-check at the top of the method does not close the race:
  `clientCtx` could still be nulled between the guard and the subsequent
  `clientCtx.getConf()` dereference. `volatile` does not help here — it
  only guarantees visibility, not atomicity across two reads. Reading the
  field once into a local variable makes the second access race-free
  (locals are not visible to other threads).

* **`timeoutQuorumWait()` — bail when already recycled.**
  Even after `maybeTimeout()` snapshots a non-null `clientCtx`,
  `recyclePendAddOpObject()` may complete before `timeoutQuorumWait()`
  acquires the monitor (both methods are `synchronized`). The pre-existing
  `if (completed) return;` guard does **not** cover this — recycling
  resets `completed` to `false`. Without an explicit null check the method
  NPEs on `lh.getLedgerMetadata()` and could invoke
  `handleUnrecoverableErrorDuringAdd` on a stale handle. Extended the
  early-return to `if (completed || lh == null || clientCtx == null)`.

### `PendingAddOpTest.java`

Four new unit tests:

| Test | What it verifies |
|---|---|
| `testMaybeTimeoutReturnsFalseWhenClientCtxIsNull` | The exact race: `clientCtx = null` must not NPE |
| `testMaybeTimeoutReturnsFalseWhenWithinQuorumTimeout` | Normal path — not yet timed out |
| `testMaybeTimeoutReturnsTrueWhenQuorumTimeoutExpired` | Normal path — timed out, `true` returned |
| `testTimeoutQuorumWaitIsNoOpWhenAlreadyRecycled` | Recycle wins the monitor race after `maybeTimeout()` already saw a non-null `clientCtx`: `timeoutQuorumWait()` must not NPE and must not invoke `handleUnrecoverableErrorDuringAdd` on the stale handle |

### CODE REVIEW

File: bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingAddOp.java [hunk 1]
```diff
@@ -154,6 +154,12 @@ private void sendWriteRequest(List<BookieId> ensemble, int bookieIndex) {
     }
 
     boolean maybeTimeout() {
+        if (clientCtx == null) {
```
Comment (merlimat) [inline bookkeeper-server/src/main/java/org/apache/bookkeeper/client/PendingAddOp.java]: I don't think this would solve the race condition completely, since it could be set to null before the next read on line 163. 

Better approach would be (even without the `volatile`) to assign to local variable and the the null there.  Still wouldn't address whether it's safe to call `timeoutQuorumWait()` if it was already recycled.

**Comment by eolivelli** [comment]
@merlimat can you please take another look ?

**Review by merlimat — APPROVED** [review]
👍
