### PR TITLE
[bookie] Fix memory leak when the Bookie is in read only mode

### LINKED ISSUE #3745: Bookie server memory leak when read-olny open
**BUG REPORT**
Use v2 protocol to add entry to server.

### 2.BookieProtoEncoding decode the byteBuf to ParsedAddRequest
https://github.com/apache/bookkeeper/blob/7b5b6b240ca7551da266903078f2dd2ba2906b96/bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieProtoEncoding.java#L477

#### 2.1 Before creating ParsedAddRequest, retain the byteBuf.
https://github.com/apache/bookkeeper/blob/7b5b6b240ca7551da266903078f2dd2ba2906b96/bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieProtoEncoding.java#L184-L187 
line_186 retain,  **the refCnt increase to 4**

#### 2.2 In the ParsedAddRequest construction, retain the byteBuf.
https://github.com/apache/bookkeeper/blob/7b5b6b240ca7551da266903078f2dd2ba2906b96/bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieProtocol.java#L313-L324 
line_322 retain, **the refCnt increase to 6**

### 3. Trigger channelRead, and send the request to BookieRequestProcessor. 
https://github.com/apache/bookkeeper/blob/7b5b6b240ca7551da266903078f2dd2ba2906b96/bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieRequestProcessor.java#L618-L648 
line_619, wrap the request by WriteEntryProcessor, then line_634, execute the WriteEntryProcessor in the threadPool, it's async, to explain the  WriteEntryProcessor detail later.

#### 4.1 After trigger channelRead, release byteBuf.
https://github.com/apache/bookkeeper/blob/7b5b6b240ca7551da266903078f2dd2ba2906b96/bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/BookieProtoEncoding.java#L471-L485
line_484 release, **the refCnt decrease to 4.** This release neutralizes 1.1 
(4.1 <===> 1.1)

### 5. WriteEntryProcessor processPacket detail
The invoke chain: BookieImpl#addEntry -> BookieImpl#addEntryInternal -> Journal#logAddEntry

https://github.com/apache/bookkeeper/blob/7b5b6b240ca7551da266903078f2dd2ba2906b96/bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/WriteEntryProcessor.java#L60-L116
in line_80, invoke BookieImpl#addEntry.

https://github.com/apache/bookkeeper/blob/7b5b6b240ca7551da266903078f2dd2ba2906b96/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java#L1080-L1111
line_1093, invoke BookieImpl#addEntryInternal.

line_981, invoke Journal#logAddEntry
https://github.com/apache/bookkeeper/blob/7b5b6b240ca7551da266903078f2dd2ba2906b96/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java#L981

#### 5.1 Before sending QueueEntry to the queue, retain ByteBuf.

https://github.com/apache/bookkeeper/blob/7b5b6b240ca7551da266903078f2dd2ba2906b96/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java#L975-L993
line_979 retain, **the refCnt increase to 6**. 

#### 5.2 After sending the byteBuf to the Journal, release byteBuf.
https://github.com/apache/bookkeeper/blob/7b5b6b240ca7551da266903078f2dd2ba2906b96/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieImpl.java#L1109
line_1109 release, **the refCnt decrease to 4**. This release neutralizes 2.2
（5.2 <==> 2.2）

#### 5.3 After sending the byteBuf to the bookie, release byteBuf.

https://github.com/apache/bookkeeper/blob/7b5b6b240ca7551da266903078f2dd2ba2906b96/bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/WriteEntryProcessor.java#L105 
line_105 release, **The refCnt decrease to 2**. This release neutralizes 2.1
(5.3 <==> 2.1)

#### 6.1 After bufferChannel write the entry, release byteBuf.
https://github.com/apache/bookkeeper/blob/7b5b6b240ca7551da266903078f2dd2ba2906b96/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/Journal.java#L1288-L1291
line_1219 release, ***The refCnt decrease to 1, it's free**. This release neutralizes 5.1
(6.1 <==> 5.1)

### 1. Bookie is in read-only mode
https://github.com/apache/bookkeeper/blob/7b5b6b240ca7551da266903078f2dd2ba2906b96/bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/WriteEntryProcessor.java#L61-L71

Before normal case section 5, the ByteBuf refCnt is 4. At line_68, release, **The refCnt decrease to 2**, then return. So memory leak.

### 2. Protocol version is not compatible
https://github.com/apache/bookkeeper/blob/7b5b6b240ca7551da266903078f2dd2ba2906b96/bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PacketProcessorBase.java#L168-L184
It returned directly, but didn't release. Also memory leak.

## Thought
In normal case 5.3, it neutralizes 2.1. But in fact, the 2.1 and 5.3 is unnecessary, we can ignore these operations.

https://github.com/apache/bookkeeper/blob/7b5b6b240ca7551da266903078f2dd2ba2906b96/bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/WriteEntryProcessor.java#L73-L106

line_80, ParsedAddRequest#data is passing to the BookieImpl#addEntry, in BookieImpl#addEntry, it release the ParsedAddRequest#data, that's reasonable.

line_105, it release ParsedAddRequest#data again, that's not reasonable. The BookieImpl will release the data, and here do the same work, it's repeated.  It is just for neutralizing 2.1.

So we can remove the 2.1 and 5.3, we just need to release the ParsedAddRequest#data once, the byteBuf will be free.

### PR DESCRIPTION
**Pull request by horizonzy**
Descriptions of the changes in this PR:
Fixes #3745

### CODE REVIEW

File: bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PacketProcessorBase.java [hunk 1]
```diff
@@ -175,7 +175,9 @@ public void run() {
             if (request instanceof BookieProtocol.ReadRequest) {
                 requestProcessor.onReadRequestFinish();
             }
-            if (request instanceof BookieProtocol.AddRequest) {
+            if (request instanceof BookieProtocol.ParsedAddRequest) {
+                ((BookieProtocol.ParsedAddRequest) request).release();
+                request.recycle();
                 requestProcessor.onAddRequestFinish();
```
Comment (wenbingshen) [inline bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PacketProcessorBase.java:181]: Can the release of ParsedAddRequest be executed in the recycle method? It seems that these two methods are always used together, and there is a forced switch here, which seems a bit awkward.

You can look at org.apache.bookkeeper.proto.BookieProtocol.AddRequest#recycle method
```java
        @Override
        public void recycle() {
            ledgerId = -1;
            entryId = -1;
            masterKey = null;
            ReferenceCountUtil.safeRelease(data);
            data = null;
            recyclerHandle.recycle(this);
        }
```

**Review by wenbingshen — COMMENTED** [review]
Good catch! 
Very detailed investigation and explanation!

File: bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PacketProcessorBase.java (hunk 1 above)
Comment (horizonzy) [reply bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PacketProcessorBase.java:181]: It can't, we shouldn't release the data in the recycle.
In the normal case, it will recycle the request, but the data is already free.

See: https://github.com/apache/bookkeeper/blob/7b5b6b240ca7551da266903078f2dd2ba2906b96/bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/WriteEntryProcessor.java#L131

Comment (wenbingshen) [reply bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PacketProcessorBase.java:181]: I saw it, sorry I misread it earlier. Nice work. Thanks.

**Review by wenbingshen — APPROVED** [review]

**Review by hangc0276 — APPROVED** [review]
Great job!

**Review by StevenLuMT — APPROVED** [review]
LGTM

**Comment by hangc0276** [comment]
@merlimat @eolivelli @dlg99 @zymap  Please help take a look at this PR, thanks.

**Review by zymap — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]
Great catch

**Review by dlg99 — APPROVED** [review]
