### PR TITLE
[ISSUE 2637] Fix jvm_memory_direct_bytes_used metrics when using jdk11+

### LINKED ISSUE #2637: The metrics about jvm_memory_direct_bytes_used
The mertics about `jvm_memory_direct_bytes_used` is acquired by netty's `PlatformDependent#DIRECT_MEMORY_COUNTER`.
Which can only acquired the memory used by netty.
How about rename `jvm_memory_direct_bytes_used` to `netty_memory_direct_bytes_used`,

And use `java.nio.Bits#RESERVED_MEMORY` for jvm direct memory metrics.

### PR DESCRIPTION
**Pull request by Shoothzj**
Fix #2637 #3247

### Motivation
The mertics about `jvm_memory_direct_bytes_used` is acquired by netty's `PlatformDependent#DIRECT_MEMORY_COUNTER`. Which can only acquired the memory used by netty.

### Changes
- use `java.nio.Bits#RESERVED_MEMORY` for jvm direct memory metrics.
- add tests to ensure `jvm_memory_direct_bytes_max` and `jvm_memory_direct_bytes_used` gets value.

### CODE REVIEW

**Comment by Shoothzj** [comment]
rerun failure checks

**Comment by Shoothzj** [comment]
@eolivelli @dlg99 @merlimat @pkumar-singh @nicoloboschi  PTAL

**Comment by Shoothzj** [comment]
rerun failure checks

File: stats/bookkeeper-stats-providers/prometheus-metrics-provider/src/main/java/org/apache/bookkeeper/stats/prometheus/PrometheusMetricsProvider.java [hunk 1]
```diff
@@ -223,9 +224,11 @@ private void registerMetrics(Collector collector) {
...
 
         try {
-            Field field = PlatformDependent.class.getDeclaredField("DIRECT_MEMORY_COUNTER");
-            field.setAccessible(true);
-            tmpDirectMemoryUsage = (AtomicLong) field.get(null);
+            Class<?> name = Class.forName("java.nio.Bits");
+            String fieldName = SystemUtils.IS_JAVA_1_8 ? "reservedMemory" : "RESERVED_MEMORY";
+            Field reservedMemory = name.getDeclaredField(fieldName);
+            reservedMemory.setAccessible(true);
+            tmpDirectMemoryUsage = (AtomicLong) reservedMemory.get(null);
```
Comment (dlg99) [inline stats/bookkeeper-stats-providers/prometheus-metrics-provider/src/main/java/org/apache/bookkeeper/stats/prometheus/PrometheusMetricsProvider.java:231]: fyi, you can use org.apache.commons.lang.reflect.FieldUtils [FieldUtils.readDeclaredField() ](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/reflect/FieldUtils.html#readField-java.lang.reflect.Field-java.lang.Object-boolean-)with forceAccess

**Comment by Shoothzj** [comment]
rerun failure checks

**Review by dlg99 — COMMENTED** [review]
Is there a more officially supported way of doing this?
mx bean or something like that.

E.g. I can't tell if this works in JDK 17 or the next one.

**Comment by dlg99** [comment]
e.g. see https://github.com/apache/bookkeeper/pull/3234 : "Starting from JDK17 the reflection is not allowed in the jdk internals modules"

**Comment by Shoothzj** [comment]
@eolivelli @merlimat @pkumar-singh @nicoloboschi PTAL @dlg99  PTAL again, thanks

**Review by dlg99 — APPROVED** [review]
LGTM

**Comment by Shoothzj** [comment]
@eolivelli @merlimat @pkumar-singh @nicoloboschi PTAL

**Comment by Shoothzj** [comment]
@eolivelli @merlimat @pkumar-singh @nicoloboschi PTAL

**Comment by Shoothzj** [comment]
@eolivelli @merlimat @pkumar-singh @nicoloboschi PTAL

**Comment by Shoothzj** [comment]
@eolivelli @merlimat @pkumar-singh @nicoloboschi PTAL

**Review by hangc0276 — APPROVED** [review]

**Review by StevenLuMT — APPROVED** [review]
nice

**Comment by horizonzy** [comment]
This may be a breaking change, after this pr. The old user who used jdk8 didn't record the direct memory metrics.
