### PR TITLE
Using a separate thread pool to execute openWithMetadata

### LINKED ISSUE #2398: LedgerOpenOp may perform connection to a bookie inside the ZooKeeper client thread
While working on BP-41 I saw this potential problem.
During OpenLedgerOp (openLedger) we are executing blocking I/O operations against the bookies in the main thread of ZooKeeper client,
This may slow down the whole processing of the client because the ZooKeeper client has only one single thread that execute callbacks.
See the stacktrace (it is not an error, it is just a dump)

Suggestions:
- use a separate thread pool in order to execute blocking I/O 

```

2020-08-14 18:46:33,190 - INFO  - [AuditorBookie-127.0.0.1:37597-EventThread:CachingBookieAddressResolver@50] - resolve 192.0.2.1:1000 current cache {127.0.0.1:44827=127.0.0.1:44827, 127.0.0.1:33607=127.0.0.1:33607, 127.0.0.1:37597=127.0.0.1:37597}
	at org.apache.bookkeeper.proto.PerChannelBookieClient.connect(PerChannelBookieClient.java:541)
	at org.apache.bookkeeper.proto.PerChannelBookieClient.connectIfNeededAndDoOp(PerChannelBookieClient.java:666)
	at org.apache.bookkeeper.proto.DefaultPerChannelBookieClientPool.intialize(DefaultPerChannelBookieClientPool.java:92)
	at org.apache.bookkeeper.proto.BookieClientImpl.lookupClient(BookieClientImpl.java:217)
	at org.apache.bookkeeper.proto.BookieClientImpl.readEntry(BookieClientImpl.java:502)
	at org.apache.bookkeeper.proto.BookieClientImpl.readEntry(BookieClientImpl.java:495)
	at org.apache.bookkeeper.proto.BookieClientImpl.readEntry(BookieClientImpl.java:489)
	at org.apache.bookkeeper.client.ReadLastConfirmedOp.initiate(ReadLastConfirmedOp.java:81)
	at org.apache.bookkeeper.client.LedgerHandle.asyncReadLastConfirmed(LedgerHandle.java:1416)
	at org.apache.bookkeeper.client.LedgerOpenOp.openWithMetadata(LedgerOpenOp.java:210)
	at org.apache.bookkeeper.client.LedgerOpenOp.lambda$initiate$0(LedgerOpenOp.java:119)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at org.apache.bookkeeper.meta.AbstractZkLedgerManager$3.processResult(AbstractZkLedgerManager.java:464)
	at org.apache.bookkeeper.zookeeper.ZooKeeperClient$19$1.processResult(ZooKeeperClient.java:994)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:598)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:510)
2020-08-14 18:46:43,243 - INFO  - [Time-limited test:Auditor@1946] - Shutting down auditor
```

### PR DESCRIPTION
**Pull request by gaozhangmin**
Fixes #2398

### CODE REVIEW

**Comment by gaozhangmin** [comment]
@eolivelli PTAL

**Comment by gaozhangmin** [comment]
rerun failure checks

File: bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerOpenOp.java [hunk 1]
```diff
@@ -86,6 +88,7 @@ public LedgerOpenOp(BookKeeper bk, BookKeeperClientStats clientStats,
         this.enableDigestAutodetection = bk.getConf().getEnableDigestTypeAutodetection();
         this.suggestedDigestType = digestType;
         this.openOpLogger = clientStats.getOpenOpLogger();
+        this.scheduler = OrderedScheduler.newSchedulerBuilder().numThreads(1).name("LedgerOpenOp").build();
```
Comment (eolivelli) [inline bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerOpenOp.java:91]: No need to create a new pool.
As we know the ledgerId we can probably use the same thread used for all the operations on the ledger

**Review by eolivelli — CHANGES_REQUESTED** [review]

File: bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerOpenOp.java (hunk 1 above)
Comment (gaozhangmin) [reply bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerOpenOp.java:91]: We cannot use executor in bk,  if bk is closed unexpectedly, the operation will never completed.

Comment (eolivelli) [reply bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerOpenOp.java:91]: we cannot start a new thread per each LederOpenOp

if the BK client closes all the pending operations must fail somehow. we should fix that
otherwise there will be other operations that will never complete

Comment (eolivelli) [reply bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerOpenOp.java:91]: "some unit test would stuck forever"

maybe  we are missing to mock the executor

**Comment by eolivelli** [comment]
how this patch related to this ?
https://github.com/apache/bookkeeper/pull/3516

**Review by eolivelli — CHANGES_REQUESTED** [review]
probably this patch is no more needed ?
with https://github.com/apache/bookkeeper/pull/3516 the problem is fixed

can you double check please ?

File: bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerOpenOp.java (hunk 1 above)
Comment (gaozhangmin) [reply bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerOpenOp.java]: fixed. @eolivelli

**Comment by gaozhangmin** [comment]
> probably this patch is no more needed ? with #3516 the problem is fixed
> 
> can you double check please ?

@eolivelli , it's not related,  we should execute `openWithMetadata` in separated thread

**Comment by gaozhangmin** [comment]
rerun failure checks

**Review by eolivelli — APPROVED** [review]
Lgtm

File: bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerOpenOp.java [hunk 2]
```diff
@@ -112,12 +112,10 @@ public void initiate() {
...
         bk.getLedgerManager().readLedgerMetadata(ledgerId)
-            .whenComplete((metadata, exception) -> {
-                    if (exception != null) {
-                        openComplete(BKException.getExceptionCode(exception), null);
-                    } else {
-                        openWithMetadata(metadata);
-                    }
+                .thenAcceptAsync(this::openWithMetadata, bk.getScheduler().chooseThread(ledgerId))
+                .exceptionally(exception -> {
+                    openComplete(BKException.getExceptionCode(exception), null);
```
Comment (eolivelli) [inline bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerOpenOp.java:117]: After thinking more...
We have to execute also this callback in a separate thread.
I suggest to use whenCompleteAsync

**Review by eolivelli — CHANGES_REQUESTED** [review]

File: bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerOpenOp.java (hunk 2 above)
Comment (gaozhangmin) [reply bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerOpenOp.java:117]: Then, we need to create a new executor here if bk is closed.

Comment (gaozhangmin) [reply bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerOpenOp.java:117]: Then, we need to create new executor here  for exception case.

Comment (eolivelli) [reply bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerOpenOp.java:117]:
```
.whenCompleteAsyncAsync((m, exception) -> {
if (exception != null) {
 openComplete(BKException.getExceptionCode(exception), null);
}  else {
this.openWithMetadata(m);
}
}, bk.getScheduler().chooseThread(ledgerId))
```

Comment (gaozhangmin) [reply bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerOpenOp.java:117]: `org.apache.bookkeeper.client.BookKeeperCloseTest#testBookKeeperAdmin`  This test will be stuck, if change made

Comment (gaozhangmin) [reply bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerOpenOp.java:117]: This happened if bk is closed, we cannot go inside `whenCompleteAsyncAsync` , because bk's scheduler is shutdown.

**Review by dlg99 — APPROVED** [review]

File: bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerOpenOp.java (hunk 2 above)
Comment (gaozhangmin) [reply bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerOpenOp.java:117]: FYI @eolivelli

**Comment by gaozhangmin** [comment]
@eolivelli  PTAL.

File: bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerOpenOp.java (hunk 2 above)
Comment (eolivelli) [reply bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerOpenOp.java:117]: So when the BK closed the treadpool is shutdown and the callback isn't executed.
This looks like a problem that can happen on every callback.

Let's keep this patch as it is here but please open a ticket to track this bad problem.

If the BK client is closed then probably the application is shutting down  and it is a critical point in the life cycle

**Review by eolivelli — APPROVED** [review]
I am approving this patch.
Please take a look to my comment.
It looks like we have a serious problem.
